---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/www"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      name: html-pod
      labels:
        app: html-app
        app-revision: v3
    spec:
      containers:
        - name: html-app
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.3"
            limits:
              memory: "128Mi"
              cpu: "0.5"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: "/usr/share/nginx/html"
              readOnly: true
      volumes:
        - name: html-volume
          persistentVolumeClaim:
            claimName: pv-claim
