apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ "pv-" }}{{ include "HtmlApp.fullname" . }}
  labels:
    {{- include "HtmlApp.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.className }}
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  hostPath:
    path: {{ .Values.storage.hostPath }}
